version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # login
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t tteoh/kasm-qgis:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push tteoh/kasm-qgis:$CIRCLE_BRANCH
