version: 2.1
jobs:
  build:
    docker:
      - image: tteoh/kasm-qgis:latest
      - auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker build -t tteoh/kasm-qgis:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push tteoh/kasm-qgis:latest
