version: 2.1
jobs:
  build:
    docker:
      - image: tteoh/kasm-qgis:$TAG
        auth:
          username: tteoh 
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t tteoh/kasm-qgis:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push tteoh/kasm-qgis:$TAG
