name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: docker login --username ${{ secrets.DOCKER_USER }} --password-stdin < ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tteoh/kasm-qgis:$(date +%s)
    - name: Publish Docker image
      run: docker push tteoh/kasm-qgis:$(date +%s)
